export const icons = {
    logo: require('../../assets/images/logo.png'),
    logotwo: require('../../assets/images/logotwo.png'),
    stethoscope: require('../../assets/images/stethoscope.png'),
    logonew: require('../../assets/images/logonew.png'),
    doctoricon: require('../../assets/images/doctoricon.png'),
    clinic: require('../../assets/images/clinic.png'),
    stetjoscopeicon: require('../../assets/images/stetjoscopeicon.png'),
    hospital: require('../../assets/images/hospital.png'),
    arrowback: require('../../assets/images/arrowback.png'),
    doctortwos: require('../../assets/images/doctortwos.png'),
    trueicon: require('../../assets/images/trueicon.png'),
    eyes: require('../../assets/images/eyes.png'),
    hidden: require('../../assets/images/hidden.png'),
    hospitalicon: require('../../assets/images/hospitalicon.png'),
    clinicicon: require('../../assets/images/clinicicon.png'),
    cliincbottom: require('../../assets/images/cliincbottom.png'),
    meds: require('../../assets/images/meds.png'),
    hamburger: require('../../assets/images/hamburger.png'),
    location: require('../../assets/images/location.png'),
    map: require('../../assets/images/map.png'),
    bell: require('../../assets/images/bell.png'),
    search: require('../../assets/images/search.png'),
    more: require('../../assets/images/more.png'),
    medicine2: require('../../assets/images/medicine2.png'),
    Rectangle: require('../../assets/images/Rectangle.png'),
    Rectangle2: require('../../assets/images/Rectangle2.png'),
    Rectangle3: require('../../assets/images/Rectangle3.png'),
    Rectangle4: require('../../assets/images/Rectangle4.png'),
    image25: require('../../assets/images/image25.png'),
    favorite: require('../../assets/images/favorite.png'),
    dr: require('../../assets/images/dr.png'),
    star: require('../../assets/images/star.png'),
    starhalf: require('../../assets/images/starhalf.png'),
    uparrow: require('../../assets/images/uparrow.png'),
    docdr: require('../../assets/images/docdr.png'),
    denti: require('../../assets/images/denti.png'),
    ayus: require('../../assets/images/ayus.png'),
    the: require('../../assets/images/the.png'),
    favorite2: require('../../assets/images/favorite2.png'),
    thumbup: require('../../assets/images/thumbup.png'),
    cardtravel: require('../../assets/images/cardtravel.png'),
    attachmoney: require('../../assets/images/attachmoney.png'),
    querybuilder: require('../../assets/images/querybuilder.png'),
    clear: require('../../assets/images/clear.png'),
    profileim: require('../../assets/images/profileim.png'),
    vertical: require('../../assets/images/vertical.png'),
    info: require('../../assets/images/info.png'),
    qa: require('../../assets/images/qa.png'),
    homtop: require('../../assets/images/homtop.png'),
    sthescop: require('../../assets/images/sthescop.png'),
    book: require('../../assets/images/book.png'),
    dateimg: require('../../assets/images/dateimg.png'),
    home: require('../../assets/images/home.png'),
    call:require('../../assets/images/call.png'),
    call:require('../../assets/images/call.png'),
    abu:require('../../assets/images/abu.png'),
    schedule:require('../../assets/images/schedule.png'),
    calendartoday:require('../../assets/images/calendartoday.png'),
    alarm:require('../../assets/images/alarm.png'),
    alarmoff:require('../../assets/images/alarmoff.png'),
    forward:require('../../assets/images/forward.png'),
    erth:require('../../assets/images/erth.png'),
    gallary:require('../../assets/images/gallary.png'),
    camera:require('../../assets/images/camera.png'),
    repotsimg:require('../../assets/images/repotsimg.png'),
    verticalalignbot:require('../../assets/images/verticalalignbot.png'),
    delete:require('../../assets/images/delete.png'),
    add:require('../../assets/images/add.png'),
    mail:require('../../assets/images/mail.png'),
    rightarrow:require('../../assets/images/rightarrow.png'),
    deletedtwo:require('../../assets/images/deletedtwo.png'),
    big:require('../../assets/images/big.png'),
    onlnine:require('../../assets/images/onlnine.png'),
    calender:require('../../assets/images/calender.png'),
    calen:require('../../assets/images/calen.png'),
    pati:require('../../assets/images/pati.png'),
    pati:require('../../assets/images/pati.png'),
    dasdor:require('../../assets/images/dasdor.png'),
    xyz:require('../../assets/images/xyz.png'),
    key:require('../../assets/images/key.png'),
    share:require('../../assets/images/share.png'),
    profileimg:require('../../assets/images/profileimg.png'),
    bordercolor:require('../../assets/images/bordercolor.png'),
    Rectangle2df:require('../../assets/images/Rectangle2df.png'),
    calenim:require('../../assets/images/calenim.png'),
    tag:require('../../assets/images/tag.png'),
    watch:require('../../assets/images/watch.png'),
    ackon:require('../../assets/images/ackon.png'),
    arrowdrop:require('../../assets/images/arrowdrop.png'),
    arrowup:require('../../assets/images/arrowup.png'),
    verticalalign:require('../../assets/images/verticalalign.png'),
    arrowup2:require('../../assets/images/arrowup2.png'),
}