export const string = {
itis:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
WelcomeBack:"Welcome",
Back:'Back',
Doctor:'Doctor',
Patient:'Patient',
Clinic:'Clinic',
Login:"Login",
Signup:"Signup",
continue:'Continue',
LoginwithEmailID:'Login with EmailID',
change:'change',
Donrecievecode:"Don’t recieve code!",
Resend:"Resend",
LOGIN:'LOGIN',
LoginwithPhonenumber:'Login with Phone number',
Forgotpassword:'Forgot password',
Pleaseent:'Please enter your registered email  ID to reset your password',
SENDEMAIL:'SEND EMAIL',
SIGNUP:"SIGNUP",
AppoloHospitals:'Appolo Hospitals',
MultispcialistHospitals:"Multispcialist Hospitals",
Itsalong:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
AkshyaAhemdabad:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Ahemdabad',
About:'About',
Premium:'PREMIUM',
Experience:"Experience: ",
consultation:'Consultation: ',
boking:'Book new',
AvilableTimings:'Avilable Timings',
Services:'Services',
HospitalAddress:'Hospital Address',
AppoloClinic:'Appolo Clinic',
MultispcialistClinic:'Multispcialist Clinic',
Multispecialist:'Multispecialist',
GeneralSurgeon:'General Surgeon',
Cardiologist:'Cardiologist',
Dentist:'Dentist',
Dermatologists:'Dermatologists',
ENTSpecialist:'ENT Specialist',
DoctorProfile:'Doctor’s Profile',
PrimeumBoook:'Primeum Boook',
Experience:'Experience',
ConsultancyFee:'Consultancy Fee',
Availability:'Availability',
Feedback:'Feedback',
Specializations:'Specializations',
Book:'Book',
home:"Home",
MyAppointments:'My Appointments',
Medicalrecords:"Medicalrecords",
FavouriteDoctors:"Favourite Doctors",
Myaddresses:'My Addresses',
ContactUs:'Contact Us',
FAQs:'FAQs',
AboutUs:'About Us',
Help:'Help',
Logout:'Logout',
TermsandConditions:"Terms and Conditions",
UpcomingAppointments:'Upcoming Appointments',
akshya:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Ahemdabad',
Lorem:'Lorem ipsum dolor sit amet',
BookedFollowup:"Booked Followup",
CancleAppointmet:'Cancle Appointmet',
Feedback:'Feedback',
CancleAppointment:'Cancle Appointment',
Ihavechangedmymind:'I have changed my mind.',
Doctorisnotavailable:'Doctor is not available.',
Others:"Others.",
Cancle:'Cancle',
Please:'Please note, we do not offer refunds. you will lose any payments you have already made. as this appointment is ',
YeIwanttocancle:'Yes, I want to cancle',
Dootcancle:'Do not cancle',
MedicalReports:'Medical Reports',
Pleaseupload:"Please upload your prescription and reports.",
UploadPrescription:'Upload Prescription',
UploadReports:'Upload Reports',
Pleaseuploadyourreport:'Please upload your report',
Gallery:'Gallery',
Camera:'Camera',
Prescription:'Prescription',
Reports:'Reports',
ReportofDiabities:'Report of Diabities',
Manishprajapati:'Manishprajapati',
BlockRammurthynagar:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Ahemdabad -560016',
TermsConditions:'Terms & Conditions',
TaC:'T & C',
CurearTERMSCONDITIONS:'Curearc TERMS & CONDITIONS',
import:"IMPORTANT:\n\n\n'THESE TERMS AND CONDITIONS (“Conditions”) DEFINE THE BASIS UPON WHICH GETT WILL PROVIDE YOU WITH ACCESS TO THE GETT MOBILE APPLICATION PLATFORM, PURSUANT TO WHICH YOU WILL BE ABLE TO REQUEST CERTAIN TRANSPORTATION SERVICES FROM THIRD PARTY DRIVERS BY PLACING ORDERS THROUGH GETT’S MOBILE APPLICATION PLATFORM. THESE CONDITIONS (TOGETHER WITH THE DOCUMENTS REFERRED TO HEREIN) SET OUT THE TERMS OF USE ON WHICH YOU MAY, AS A CUSTOMER, USE THE APP AND REQUEST TRANSPORTATION SERVICES. BY USING THE APP AND TICKING THE ACCEPTANCE BOX, YOU INDICATE THAT YOU ACCEPT THESE TERMS OF USE WHICH APPLY, AMONG OTHER THINGS, TO ALL SERVICES HEREINUNDER TO BE RENDERED TO OR BY YOU VIA THE APP WITHIN THE UK AND THAT YOU AGREE TO ABIDE BY THEM. USE THE APP AND REQUEST TRANSPORTATION SERVICES. BY USING THE APP AND TICKING THE ACCEPTANCE BOX, YOU INDICATE THAT YOU ACCEPT THESE TERMS OF USE WHICH APPLY, AMONG OTHER THINGS, TO ALL SERVICES HEREINUNDER TO BE RENDERED TO OR BY YOU VIA THE APP WITHIN THE UK AND THAT YOU AGREE TO ABIDE BY THEM.",
Account:'Account',
Unblockaccount:'Unblock account',
Changephonenumber :'Change phone number ',
Changephonenumber :'Change phone number ',
Privacyinformation:'Privacy information',
Acceptedpaymentmethods:"Accepted payment methods",
Priceestimation:'Price estimation',
Cancellationfee:'Cancellation fee',
Loremipsum:'Lorem ipsum',
Paymentandpricing:'Payment and pricing',
Notifications:'Notifications',
adminAdd:'Admin Added',
readable:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
flatdiscount:'10% flat discount',
Youwononecoupen:'You won one coupen',
whatisyourating:'What is you rate?',
Pleaseshareyourfeedback:'Please share your feedback',
Send:'Send',
RemedoDoctor:'Remedo Doctor',
Welcome :'Welcome' ,
OnlinePatient:'Offline Patient',
Calender:'Calender',
Report:'Report',
ManageProfile:'Manage Profile',
Dashboard:'Dashboard',
Holiday:"Holiday / Block calender ",
ChangePassword:'Change Password',
Share:'Share',
Viewandeditprofile:"View and edit profile",
complete:'90% complete',
Mo:'MO :',
age:'Age :',
Gender :'Gender :',
LoremIpsumissimply :"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
SeenByDoctor:'Seen By Doctor',
notsceen:'Not Seen',
AddOfflinePatient:'Add Offline Patient',
add:"Add",
Profile:'Profile',
mss:'MBBS, MD \n Gynecologist/Obstretrician \n 11 years experien',
AvilableTime:'Avilable Time',
bookfor:'Book For',
ConfirmBook:'Confirm Book',
Payatclinic:'Pay at clinic',
PaynowBook:'Pay now & Book',
PremiumBook:"Premium Book",
PremiumBookBenefits:'Premium Book Benefits',
Instantminutes:'Instant appointment \n (Wait time upto 15 minutes)',
Appointmentwit:'Appointment with same Doctor.',
FixedConsultationFee:'Fixed Consultation Fee',
feeatclinic:'*Pay premium charges now and \n  consultation fee at clinic',
Not:'Note: Premium charges will be Non-refundable If appointment is cancelled by patient or incase of Patient no show if booked under premium booking. As the doctor reserves/Blocks the time slot for your instant appointment.',
Yourappointmentwith  :'Your appointment with DR. SHAH has been confirmed on 11 Nov 2020 Tue 3:00 PM. ',
MyAppointments:"My Appointments",
Reports:'Reports',
clinicIndiranagar:'Shree satya sai clinic, Indira nagar',
Appointments:'Appointments',
Calender:'Calender',
Appololorem:'Appolo lorem  ipsum..',
drshaha:'Dr. Shah',
Attended:'Attended',
NotAttended:'Not Attended',
BlockCalender:'Block Calender'
}